apiVersion: apps/v1
kind: Deployment
metadata:
  name: asue1-dptweb-deployment
  labels:
    app: asue1-dptweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: asue1-dptweb
  template:
    metadata:
      labels:
        app: asue1-dptweb
    spec:
      containers:
        - name: asue1-dptweb-container
          image: asue1/dptweb:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: asue1-dptweb-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Node's external port
  selector:
    app: asue1-dptweb

